apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-chart.name" . }}
  labels:
    app: {{ include "demo-chart.name" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ include "demo-chart.name" . }}
